### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by epic2305** [pratishrai/doraemon#9]
when i try to run some of the files dont work is there something i am missing or is the code broken fyi i am epic is here#zero zero zero one
![Screenshot (113)](https://user-images.githubusercontent.com/77462806/110705982-64ca2d80-81b4-11eb-88bc-240e52120534.png)
![Screenshot (114)](https://user-images.githubusercontent.com/77462806/110705998-698ee180-81b4-11eb-92fb-56760ddc8611.png)

**Comment by pratishrai** [comment]
Hey @epic2305, please follow these steps https://github.com/pratishrai/doraemon#setup and it should work
